### PR TITLE
Use 10.9 as the minimum version

### LINKED ISSUE #8: MPFR is compiled with thread-safe mode disabled.
Configure script determines that clang doesn't support TLS here, https://travis-ci.org/conda-forge/mpfr-feedstock#L481-L482

### PR DESCRIPTION
**Pull request by isuruf**
Fixes #8 as well
Rerendered

### CODE REVIEW

**Comment by isuruf** [comment]
@jakirkham, can you take a look?

**Comment by isuruf** [comment]
ping

**Comment by jakirkham** [comment]
Sorry @isuruf have been pretty swamped this week and expect the trend to continue over the next couple weeks, but am looking while I have a little bit of time.

This PR looks good. The one suggestion I have is we move from setting all these environment variables directly to using the [`toolchain`](https://github.com/conda-forge/toolchain-feedstock). It should cutdown our maintenance burden going forward and help standardize things across conda-forge a bit more.

**Comment by jakirkham** [comment]
Thanks @isuruf . 😀

**Pull request merged**
