### PR TITLE
Update to 4.2.0

### PR DESCRIPTION
**Pull request by jschueller**
@conda-forge-admin please rerender

### CODE REVIEW

**Comment by jschueller** [comment]
ping @conda-forge/mpfr

**Comment by jschueller** [comment]
ping https://github.com/orgs/conda-forge/teams/mpfr

**Comment by jschueller** [comment]
it's been a while @conda-forge/mpfr

**Comment by jschueller** [comment]
ping @jakirkham @marcelotrevisani @isuruf, it's been a while

**Comment by isuruf** [comment]
Thanks. Sorry about the delay.

**Pull request merged**
